import type { Project } from "@/types";

/** Fixtures for the dev-only /preview harness. The real showcase reads Supabase. */
export const PREVIEW_PROJECTS: Project[] = [
  {
    id: "b2000000-0000-4000-8000-000000000001",
    user_id: null,
    title: "FailSafe AI",
    description: null,
    ai_summary:
      "Multi-agent security review system that catches vulnerabilities across a codebase before they reach production.",
    tech_stack: ["Python", "LangGraph", "FastAPI"],
    tags: ["ai", "security", "agents"],
    looking_for: ["Frontend Dev"],
    github_url: "https://github.com/example/failsafe",
    demo_url: null,
    image_url: null,
    status: "looking-for-team",
    created_at: "2026-08-20T10:00:00+05:30",
  },
  {
    id: "b2000000-0000-4000-8000-000000000002",
    user_id: null,
    title: "IPL Draft Simulator",
    description: null,
    ai_summary:
      "Role-based auction simulator that models team budgets and bidding strategy across a full IPL draft.",
    tech_stack: ["Next.js", "FastAPI", "PostgreSQL"],
    tags: ["web-dev", "simulation", "sports"],
    looking_for: [],
    github_url: "https://github.com/example/ipl-draft",
    demo_url: "https://ipl-draft.example.com",
    image_url: null,
    status: "completed",
    created_at: "2026-07-11T10:00:00+05:30",
  },
  {
    id: "b2000000-0000-4000-8000-000000000003",
    user_id: null,
    title: "MuleNet",
    description: null,
    ai_summary:
      "Mesh networking layer that keeps messages moving between devices when there is no internet connection available.",
    tech_stack: ["Rust", "WebRTC", "React"],
    tags: ["networking", "iot", "systems"],
    looking_for: ["ML Engineer", "Designer"],
    github_url: null,
    demo_url: null,
    image_url: null,
    status: "looking-for-team",
    created_at: "2026-08-28T10:00:00+05:30",
  },
  {
    id: "b2000000-0000-4000-8000-000000000004",
    user_id: null,
    title: "Campus Crop Vision",
    description: null,
    ai_summary:
      "Vision model that grades leaf disease severity from phone photos, trained on a dataset collected around campus.",
    tech_stack: ["PyTorch", "Flask", "React Native"],
    tags: ["ai", "ml", "mobile"],
    looking_for: ["Mobile Dev"],
    github_url: "https://github.com/example/crop-vision",
    demo_url: null,
    image_url: null,
    status: "active",
    created_at: "2026-08-15T10:00:00+05:30",
  },
  {
    id: "b2000000-0000-4000-8000-000000000005",
    user_id: null,
    title: "Typing Test Arena",
    description: null,
    ai_summary:
      "Real-time multiplayer typing race with per-keystroke accuracy analytics and a live campus leaderboard.",
    tech_stack: ["Svelte", "Socket.IO", "Redis"],
    tags: ["web-dev", "realtime", "games"],
    looking_for: [],
    github_url: "https://github.com/example/typing-arena",
    demo_url: "https://typing.example.com",
    image_url: null,
    status: "completed",
    created_at: "2026-06-30T10:00:00+05:30",
  },
  {
    id: "b2000000-0000-4000-8000-000000000006",
    user_id: null,
    title: "BlockTicket",
    description: null,
    ai_summary:
      "Tamper-proof event ticketing on-chain, built to stop resale fraud at college fests and inter-college meets.",
    tech_stack: ["Solidity", "Next.js", "Ethers.js"],
    tags: ["blockchain", "web-dev"],
    looking_for: ["Designer"],
    github_url: null,
    demo_url: null,
    image_url: null,
    status: "looking-for-team",
    created_at: "2026-08-05T10:00:00+05:30",
  },
];
